### PR TITLE
Add support for service dependency check type

### PR DESCRIPTION
**Pull request by rauhut**
Adds create and update support for our service dependency check type (This check is quite simple and doesn't have any additional arguments to the base check type)

### CODE REVIEW

**Comment by eochoa260** [comment]
Changes look good to me.  Tried testing them out in graphql in staging but it seems that these mutations aren't public yet?

**Review by rocktavious — APPROVED** [review]
Flawless change @rauhut 🎉 

When will the APIs be made public?

**Comment by rauhut** [comment]
> Flawless change @rauhut 🎉
> 
> When will the APIs be made public? Our intention is to cut a release of this Friday - will the APIs be public then? If not we should not merge untill after Friday.

cc: @eochoa260 

I checked with Scott, we will be making the mutations public today. I'll let you know once the change is in

**Comment by rauhut** [comment]
@rocktavious @eochoa260 the create and update mutations are now public in GraphQL

**Comment by rocktavious** [comment]
Thanks @rauhut - Everything looks great.  Feel free to do the honors of merging this amazing PR - otherwise i'll merge it before we cut the next release.

**Pull request merged**
